version: '3.7'
services:
  react:
    container_name: react
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile-react
    volumes:
      - ./react:/app
    depends_on:
      - api
    networks:
      - redeagle
    ports:
      - 3000:3000
    expose:
      - 3000

  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile-elixir
    volumes:
      - .:/elixir
    environment:
      - APP=elixir
    depends_on:
      - db
    networks:
      - redeagle
    ports:
      - 4000:4000
    expose:
      - 4000
  db:
    image: postgres:11.5
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - redeagle
    ports:
      - 5433:5432
networks:
  redeagle:
