FROM node:13-alpine

RUN mkdir -p /app

COPY ./react /app

WORKDIR /app

RUN npm install --silent

ENV PATH /app/node_modules/.bin:$PATH

RUN npm install react-scripts@3.3.1 -g --silent

CMD ["npm", "start"]    